repos:
  - repo: local
    hooks:
      - id: changeset-json-check
        name: Validate changeset JSON
        entry: |
          bash -c '
          changeset_files=$(find ./.changeset -type f -name "*.json");
          if [[ -n "$changeset_files" ]]; then
            echo "Validation passed for changeset JSON files.";
            exit 0;
          else
            echo "Error: No changeset JSON files found in .changeset folder!";
            exit 1;
          fi
          '
        language: system
        files: ''
