repos:
  - repo: local
    hooks:
      - id: validate-changelog-json
        name: Validate changelog.json
        entry: ./scripts/validate_changelog.sh
        language: system
        stages: [commit]
        files: ^changelog.json$
