name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build binary
        run: go build -o changelog-forge

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: changelog-forge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
