name: Go Build Workflow

on:
  workflow_run:
    workflows: ["Go Test Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build binary
        run: |
          mkdir -p build
          go build -o build/changelog-forge ./cmd

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog-forge-binary
          path: build/changelog-forge
