name: Go Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    # Step 3: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 4: Run tests
    - name: Run tests
      run: go test ./... -v